### ISSUE TITLE
New maintainer(s) needed

### ISSUE THREAD

**Issue by wjt** [flathub/com.anydesk.Anydesk#109]
I am the only active (relatively speaking) committer to this repo. I don't use Anydesk myself and have no particular reason any more to keep it ticking along, particularly since there is a steady stream of reported issues. I have previously tried and failed to make contact with anyone at Anydesk about the existence of this wrapper.

I will open a draft PR to mark the app as EOL, which I will merge in about 4 weeks if no-one steps forward to triage issues & review PRs. I will also ask the Flathub team to remove me as a committer in 4 weeks.

**Comment by andreasknoben** [comment]
Hi, only just saw this post. I have absolutely no experience with maintaining packages so I can only thank you for your work. Thanks again and take care.

**Comment by maplehobo** [comment]
I noticed today that AnyDesk was no longer available on flathub. The deb build from their official site was giving me issues but the flatpak version runs flawlessly. Thank you very much for your work. What happens now with the AnyDesk flatpak I have installed, should I uninstall it? If no one takes over then I gather it could become a security concern?

**Comment by wjt** [comment]
Broadly speaking I would say that the EOLed Flatpak that you have installed is no less secure than the deb or generic-Linux tarball you can download from Anydesk, right now. But yes, if new releases of Anydesk (or the bundled dependencies in the Flatpak) fix security flaws, you won't get those.

**Comment by der-eismann** [comment]
I would like to take over maintenance for this repository, but I have no idea how this works in regard to GitHub permissions. Is this done by someone manually?

**Comment by kowalski7cc** [comment]
If you need help, I have some experience with flatpaks :slightly_smiling_face:
