### ISSUE TITLE
Login button on Gnome Fedora

### ISSUE THREAD

**Issue by slayrj** [flathub/com.anydesk.Anydesk#122]
The Login button don't show up in Fedora Gnome

![Captura de tela de 2023-12-06 12-44-42](https://github.com/flathub/com.anydesk.Anydesk/assets/17052145/9c40e6bd-62cb-4c42-aa70-76fb02b89836)

**Comment by der-eismann** [comment]
Hmm, what login button do you mean? Do you have an example where it is visible? If you compare it to Windows, keep in mind that Linux only has v6, not sure if there is any login capability.

**Comment by slayrj** [comment]
This button, if there is no login capabilities, how can I use it? I paid for Solo-1 for nothing?

![Captura de tela de 2023-12-06 13-24-21](https://github.com/flathub/com.anydesk.Anydesk/assets/17052145/93b163c9-62ee-4421-9a13-198d8250e0c1)
