### ISSUE TITLE
Anydesk breached

### ISSUE THREAD

**Issue by Pirateguybrush** [flathub/com.anydesk.Anydesk#130]
Hello,

With the recent breach, is this flatpack fully updated?  Is it risky to continue using?

https://www.bleepingcomputer.com/news/security/anydesk-says-hackers-breached-its-production-servers-reset-passwords/

**Comment by der-eismann** [comment]
Hello, the currently used version 6.3.0 was released on [10 Aug 2023](https://anydesk.com/en/changelog/linux#Version-6-3-0_card) and there has been no update for Linux since then. Also this version does not support any form of login, so I don't expect any security issues on this version.
