### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Jhovala** [flathub/com.anydesk.Anydesk#144]
It was working fine until it stopped working, I restarted the PC and it didn't start anymore.

flatpak run com.anydesk.Anydesk 
Gtk-Message: 08:46:52.566: Failed to load module "atk-bridge"
Gtk-Message: 08:46:52.650: Failed to load module "atk-bridge"

sudo apt install libatk-adaptor
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libatk-adaptor is already the newest version (2.46.0-5).
libatk-adaptor set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

OS: debian 12
CPU: ryzen 5600
RAM: 2x32gb 64gb kit

GPU: glxinfo | grep NVIDIA
server glx vendor string: NVIDIA Corporation
client glx vendor string: NVIDIA Corporation
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 535.183.01
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL version string: 4.6.0 NVIDIA 535.183.01
OpenGL shading language version string: 4.60 NVIDIA
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 535.183.01

**Comment by ivan-gj** [comment]
Hi, I just realised mine isn't working either, and although the messaging is different, there seems to be something clearly wrong with whatever this "atk" thing is. 
```
No UTF-8. Trying to change locale.
Locale sucessfully changed.
No UTF-8. Trying to change locale.
Locale sucessfully changed.
No UTF-8. Trying to change locale.
Locale sucessfully changed.

(process:10): Gtk-WARNING **: 17:51:57.632: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 17:51:57.635: Failed to load module "atk-bridge"

(process:2): Gtk-WARNING **: 17:51:57.655: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 17:51:57.658: Failed to load module "atk-bridge"
```

My specs,
- Operating System: Debian GNU/Linux 12
- Kernel Version: 6.1.0-25-amd64 (64-bit)
- Graphics Platform: wayland
- `flatpak`: 1.14.10

**Comment by GabePoel** [comment]
I'm also having these issues. For what it's worth, I've still been able to run AnyDesk by switching it to the 24.08 runtime.

So, the command `flatpak run --runtime=org.freedesktop.Platform/x86_64/24.08 com.anydesk.Anydesk` has worked for me. ¯\_(ツ)_/¯

**Comment by der-eismann** [comment]
I can confirm this issue, thanks for bringing this up and thanks for the workaround (which works for me as well) @GabePoel! I wasn't aware that the 24.08 runtime was released, I opened #145 to update it, however the [pangox compilation seems to be broken](https://buildbot.flathub.org/#/builders/25/builds/18289/steps/7/logs/stdio) at the moment.
Also no idea why the 23.08 runtime stopped version. My spare time is a bit limited, if somebody wants to dig deeper this would be very welcome!

**Comment by robastala** [comment]
Same problem... how would I adapt GabePoell command for Ubuntu 22.04

OS: Ubuntu jammy 22.04 x86_64
Kernel: 6.8.0-40-generic
DE: Gnome 42.9
WM: Mutter (X11)

**Comment by DanielLazaro1555** [comment]
También tengo ese problema. Creo que una actualización pudo haber causado esto, ¿verdad?

**Comment by flaubert-dev** [comment]
Here also the same problem. It was working yesterday. 
Today when I tried to open AnyDesk on Endless OS 6 it closes automatically 😱

**Comment by DanielLazaro1555** [comment]
En ubuntu y Zorin Os también esta fallando :(

**Comment by der-eismann** [comment]
@DanielLazaro1555 please comment in English.

Really weird that it started to happen so suddenly.

**Comment by der-eismann** [comment]
I just pushed an update to AnyDesk 6.3.3, which was released 3 days ago (but of course it's not listed on the [download site](https://download.anydesk.com/linux/), thanks AnyDesk :roll_eyes:). For me it started working again, although in the changelog they only mention:
> Improved overall handling of expired licenses

It will take a while until this update is pushed and available everywhere, but I'd be happy to get some feedback if it helps. If you need it urgently you can also try the command from https://github.com/flathub/com.anydesk.Anydesk/pull/147#issuecomment-2365049825.

**Comment by TomaszGasior** [comment]
@der-eismann I confirm that it's fixed on my machine too after last update.

**Comment by flaubert-dev** [comment]
@der-eismann I tested it on Endless OS 6 and it works perfectly again, thank you very much!! 🥳 ✅
