### ISSUE TITLE
nothing provides libgtkglext-x11-1_0-0 needed by anydesk-6.3.2-1.x86_64 from anydesk

### ISSUE THREAD

**Issue by ShadowMaster971** [flathub/com.anydesk.Anydesk#146]
I can't install and use AnyDesk on Fedora 40, du to this error.
This library is no longer needed and is deprecated.

Can you do someting?

**Comment by der-eismann** [comment]
You're trying to install the RPM package on Fedora, not the Flatpak. We can't provide support for this, sorry.
