### ISSUE TITLE
Broken download from anydesk link 

### ISSUE THREAD

**Issue by negagen** [flathub/com.anydesk.Anydesk#21]
`Failed to instalar com.anydesk.Anydesk: Mientras se descargan https://download.anydesk.com/linux/anydesk-5.4.1-amd64.tar.gz: Server returned status 404: Not Found`

**Comment by wjt** [comment]
Please test #20.

**Comment by negagen** [comment]
> Please test #20.

It worked thanks!

**Comment by Anonim19992** [comment]
Error: Во время загрузки https://download.anydesk.com/linux/anydesk-5.4.1-amd64.tar.gz: Server returned status 404: Not Found

https://download.anydesk.com/linux/anydesk-5.5.0-amd64.tar.gz - from anydesk site gives such a download link.
