### ISSUE TITLE
eu-elfcompress

### ISSUE THREAD

**Issue by Anonim19992** [flathub/com.anydesk.Anydesk#22]
where am i doing wrong?

compressing debuginfo in: /home/anton/flatpak-master/Anydesk/.flatpak-builder/rofiles/rofiles-PqBqgj/files/lib/libXmu.so.6.2.0
Warning: eu-elfcompress not installed, will not compress debuginfo
stripping /home/anton/flatpak-master/Anydesk/.flatpak-builder/rofiles/rofiles-PqBqgj/files/lib/libXmu.so.6.2.0 to /home/anton/flatpak-master/Anydesk/.flatpak-builder/rofiles/rofiles-PqBqgj/files/lib/debug/lib/libXmu.so.6.2.0.debug
Error: module libxmu: Не удалось выполнить процесс-потомок «eu-strip» (Нет такого файла или каталога)

**Comment by wjt** [comment]
@Anonim19992 if you are trying to build the PR to update to the new release, you don't need to -- the released Flatpak should now work.

Otherwise, please include more information– what command are you running? What is the full output?

**Comment by Anonim19992** [comment]
"flatpak-builder --repo=repo --force-clean build com.anydesk.Anydesk.json
flatpak remote-add --user --no-gpg-verify anydesk-repository repo
flatpak install --user --assumeyes anydesk-repository com.anydesk.anydesk"

this error occurs when executing the "flatpak-builder --repo = repo --force-clean build com.anydesk.Anydesk.json" script

**Comment by Anonim19992** [comment]
flatpak --version
Flatpak 1.4.3

**Comment by Anonim19992** [comment]
log
[Пустой документ 2.txt](https://github.com/flathub/com.anydesk.Anydesk/files/3885416/2.txt)

**Comment by Anonim19992** [comment]
Where am I doing wrong?

**Comment by wjt** [comment]
> Warning: eu-elfcompress not installed, will not compress debuginfo
> Error: module libxmu: Не удалось выполнить процесс-потомок «eu-strip» (Нет такого файла или каталога)

Have you tried installing the package on your distro which provides the two commands mentioned in this warning and error message, `eu-elfcompress` and `eu-strip`? On Debian-like systems it's `elfutils`, and the `flatpak-builder` package recommends but does not hard-depend on it.

Closing this since I don't think it's anything to do with this specific Flatpak manifest.
