### ISSUE TITLE
Remote users can't connect to Fedora out of the box

### ISSUE THREAD

**Issue by DanMan** [flathub/com.anydesk.Anydesk#25]
Maybe it's a firewall thing? Do I have to configure something first? Can you please give instructions?

I'm on Fedora 31.

**Comment by wjt** [comment]
Can you try installing the Fedora package from https://anydesk.com/en/downloads/linux and see if you can reproduce the issue with that package? If so, please contact AnyDesk support – this Flatpak is an unofficial wrapper. If not, please reopen this ticket.
