### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Surendrajat** [flathub/com.anydesk.Anydesk#33]
Anydesk spawns off many local-services, in case I lose connection momentarily, which take up ~40% of the CPU. 

System details
- OS: elemetaryOS Hera 5.1.2
- CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
- RAM: 16GB

![Screenshot from 2020-03-01 10-52-53](https://user-images.githubusercontent.com/11215000/75620205-d5a33680-5bab-11ea-850b-a4c18ebec92b.png)

**Comment by wjt** [comment]
Assuming this is reproducible outside Flatpak, report the issue to Anydesk. This is an unofficial wrapper and there's nothing we can do about application bugs

**Comment by Surendrajat** [comment]
No. It's not reproducible with the official deb package. I've recently switched to flatpak and just tested the official version again.
Observations:
- Flatpak version of anydesk keeps spawning `--local-service` processes like there's no tomorrow, each time with new PID.
- The official version of anydesk uses a single `--service` process which keeps running without any impact in all cases.

**Comment by atleta** [comment]
Indeed, it does happen with the official deb package, too. At least with 6.1.1.

![Selection_01726](https://user-images.githubusercontent.com/6267837/117287094-4312bd00-ae6a-11eb-8f5b-d9726ac865f6.png)

It seems to crazy when it cannot connect to the remote side. Or the other way around. I have a remote desktop I'm trying to connect to and around the time the other side accepts the connection it jumps to 100% CPU. I did manage to connect once or twice but it happened *before* I maneged to connect successfully, then I had a working connection (for the Nth try) for about half an hour and now I can't connect again. The guy on the other side says he does accept my connection request. What I see is that on my side is stuck at "Connection in progress. Please wait."

If I cancel the request it still keeps spinning the CPU @ 100%, but I can make a request again and the other side will see and be able to accept the request. (Yet it won't connect.)
