### ISSUE TITLE
Error while downloading for installation

### ISSUE THREAD

**Issue by Epaxa2** [flathub/com.anydesk.Anydesk#38]
It downloads up to 32% and the it reports an error:

error: Failed to install com.anydesk.Anydesk: While downloading https://download.anydesk.com/linux/anydesk-5.5.4-amd64.tar.gz: Server returned status 404: Not Found

**Comment by wjt** [comment]
merged #37, could you try again in a few hours and close this ticket if it works?

**Comment by Epaxa2** [comment]
Wow, that was fast! I will keep trying during the day.

**Comment by ivonenchev** [comment]
I have the same issue on OpenSuse Tumbleweed : 
It downloads it reports an error:

error: Failed to install com.anydesk.Anydesk: While downloading https://download.anydesk.com/linux/anydesk-5.5.4-amd64.tar.gz: Server returned status 404: Not Found

**Comment by wjt** [comment]
I published the new build and it installs OK. Reopen if problem persists.

**Comment by Epaxa2** [comment]
It works fine, thank you!
