### ISSUE TITLE
5.5.6 no longuer available, 5.5.6-1 is the available one

### ISSUE THREAD

**Issue by Progdrasil** [flathub/com.anydesk.Anydesk#44]
I'm getting an error while installing this package. It is expecting to find the package at the following url: `Error: While downloading https://download.anydesk.com/linux/anydesk-5.5.6-amd64.tar.gz: Server returned status 404: Not Found` However after inpecting the url, the latest version is 6.0.0 as contributed in #43. or the version available for 5.5.6 is with the trailing `-1` so the url that should be used for this version is now `https://download.anydesk.com/linux/generic-linux/anydesk-5.5.6-amd64.tar.gz`.

Either please update the merge request #43  or change the link please, because as it stands this package is now un installable

**Comment by wjt** [comment]
https://discourse.flathub.org/t/help-wanted-with-existing-anydesk-flatpak/289

**Comment by wjt** [comment]
Merged #43 without testing.
