### ISSUE TITLE
Flatpak version doesn't launch in KDE wayland session

### ISSUE THREAD

**Issue by parithy** [flathub/com.anydesk.Anydesk#57]
flatpak run com.anydesk.Anydesk

(process:2): GLib-GObject-WARNING **: 20:13:37.282: invalid (NULL) pointer instance

(process:2): GLib-GObject-CRITICAL **: 20:13:37.282: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:2): GLib-GObject-WARNING **: 20:13:37.282: invalid (NULL) pointer instance

(process:2): GLib-GObject-CRITICAL **: 20:13:37.282: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:6): GLib-GObject-WARNING **: 20:13:37.304: invalid (NULL) pointer instance

(process:6): GLib-GObject-CRITICAL **: 20:13:37.304: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:6): GLib-GObject-WARNING **: 20:13:37.304: invalid (NULL) pointer instance

(process:6): GLib-GObject-CRITICAL **: 20:13:37.304: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
 sh: line 1: lsb_release: command not found

**Comment by Surendrajat** [comment]
> sh: line 1: lsb_release: command not found

Did you try installing this?

**Comment by parithy** [comment]
this ticket can be closed. issue is not seen in   6.1.1
