### ISSUE TITLE
AnyDesk (com.anydesk.Anydesk 6.2.0) would not start after update

### ISSUE THREAD

**Issue by MindlessDreams** [flathub/com.anydesk.Anydesk#76]
Hello, after the update to 6.2 the flatpak would not start. This is the error Im getting. Kindly advise. Thank you!

flatpak run com.anydesk.Anydesk

(process:2): GLib-GObject-WARNING **: 17:20:07.552: invalid (NULL) pointer instance

(process:2): GLib-GObject-CRITICAL **: 17:20:07.552: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:2): GLib-GObject-WARNING **: 17:20:07.552: invalid (NULL) pointer instance

(process:2): GLib-GObject-CRITICAL **: 17:20:07.552: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:6): GLib-GObject-WARNING **: 17:20:07.615: invalid (NULL) pointer instance

(process:6): GLib-GObject-CRITICAL **: 17:20:07.615: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:6): GLib-GObject-WARNING **: 17:20:07.615: invalid (NULL) pointer instance

(process:6): GLib-GObject-CRITICAL **: 17:20:07.615: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
sh: line 1: lsb_release: command not found
Gtk-Message: 17:20:07.677: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:20:07.731: Failed to load module "canberra-gtk-module"

**Comment by MindlessDreams** [comment]
Would not start nor under Wayland nor under X11. Base system is Fedora Silverblue 36, Gnome 42.2. It has been working flawlessly until now.

**Comment by rafaelameijeiras** [comment]
Same problem here, steamdeck in my case.

**Comment by skdmev** [comment]
Same problem,  Fedora 36, Gnome 42.2

**Comment by stojshic** [comment]
Same problem. Fedora 36 with Gnome 42.2 :/

**Comment by MindlessDreams** [comment]
I installed distrobox, got an Ubuntu container and installed Anydesk deb in it - does run but hope the flatpak would work too.

**Comment by rafaelameijeiras** [comment]
is it possible to install a previous working version with flatpak comand?

**Comment by TheOne988** [comment]
Same exact error on Fedora 36 Gnome 42.2

**Comment by TheOne988** [comment]
> is it possible to install a previous working version with flatpak comand?

Yes you can change (downgrade) the version until the issue is fixed. You can do it by these steps in the terminal:

1. flatpak remote-info --log flathub com.anydesk.Anydesk
This will list all available version with additional info. You will need to find the version you want to install (Date: 2022-06-27 19:16:36 - latest working version) and copy the Commit number.
2. sudo flatpak update --commit=INSERT_COMMIT_NUMBER_HERE com.anydesk.Anydesk

After this you will have working AnyDesk. Just don't update it until the issue is not fixed. If your app gets updated automatically you can run the commands again.

Cheers

**Comment by MindlessDreams** [comment]
> In the meantime until there is a fix don't update the app. If your app gets updated automatically you can run the commands again.

Thank you, much appreciated!

**Comment by rafaelameijeiras** [comment]
> 1. flatpak remote-info --log flathub com.anydesk.Anydesk

@TheOne988 you are amazing!!, thanks

**Comment by bhibb** [comment]
> > is it possible to install a previous working version with flatpak comand?
> 
> Yes you can change (downgrade) the version until the issue is fixed. You can do it by these steps in the terminal:
> 
>     1. flatpak remote-info --log flathub com.anydesk.Anydesk
>        This will list all available version with additional info. You will need to find the version you want to install (Date: 2022-06-27 - latest working version 6.1.1) and copy the Commit number.
> 
>     2. sudo flatpak update --commit=INSERT_COMMIT_NUMBER_HERE com.anydesk.Anydesk
> 
> 
> In the meantime until there is a fix don't update the app. If your app gets updated automatically you can run the commands again.
> 
> Cheers

Thank you for the work around! This saved me today.

**Comment by tkriviradev** [comment]
Thank you for the fix.

**Comment by DevDorrejo** [comment]
have the issue, thanks.

**Comment by esa1975** [comment]
It seems like many others are having the same issue and I am as well. I don't have anything new to add. If you need me to provide any further information please let me know. In the meantime, thank you to all those who have provided workarounds.

**Comment by GabrielLasso** [comment]
Same happening here, thanks for the workarrounds

**Comment by gecko131** [comment]
Une mise à jour est publiée le 20 juillet 2022 et fonctionne parfaitement (sous Manjaro et Solus). Super boulot ! Merci :)

**Comment by Pirateguybrush** [comment]
Acknowleding there's a risk in installing software that's no longer maintained, is it possible to install this still?  If so, how?

**Comment by wjt** [comment]
```
flatpak install flathub com.anydesk.Anydesk
```

**Comment by Pirateguybrush** [comment]
Thanks!
