### ISSUE TITLE
re-update to 6.2.0

### ISSUE THREAD

**Issue by wjt** [flathub/com.anydesk.Anydesk#79]
In #78 I reverted the recent update to 6.2.0 because it crashed on startup. The newer version should be made available, in working form, here.

https://anydesk.com/en/changelog/linux doesn't give any clear pointers of the form 'crashes if x'.

**Comment by CodeCubeNeo** [comment]
Any update on this

**Comment by wjt** [comment]
No! I tried contacting AnyDesk for help, no dice.

**Comment by PlatonB** [comment]
@wjt The 6.2.1 changelog contains at minimum these fixes:
> Fixed a deadlock when starting a session
> Fixed a crash when running on Gnome

Will you try updating flatpak again?

**Comment by wjt** [comment]
Try building & testing the branch on https://github.com/flathub/com.anydesk.Anydesk/pull/92

**Comment by PlatonB** [comment]
I have now tested /pull/94 build on Gnome OS 43. Indeed, the program does not launch(.

Offtop: are there any plans to flatpakize TeamViewer?

**Comment by kukabu** [comment]
I think I found why anydesk doesn't run, but I don't understand how it's fix :(

$ fgrep libgtkglext-x11-1.0.so ~/.anydesk/anydesk.trace 
  error 2022-12-01 08:03:12.211   frontend   main     88     88                      base.dyn_library - Unable to load library libgtkglext-x11-1.0.so (Reason: libgtkglext-x11-1.0.so.0.0.0: cannot open shared object file: No such file or directory)

The librery is exists in package but anydesk can't find it.
